In [1]:
import pandas as pd

In [2]:
#metadata = pd.read_csv('singlecell.csv', sep=',')
metadata = pd.read_csv('ec_mdata.csv', sep=',')

In [3]:
barcode = metadata[metadata.columns[0]]

In [4]:
barcode

0        AAACGAAAGAGAGTAG-1
1        AAACGAAAGCACGTAG-1
2        AAACGAAAGCATGTGG-3
3        AAACGAAAGCTCGGCT-4
4        AAACGAAAGGATATCA-4
                ...
34477    TTTGTGTTCGTGGGTC-3
34478    TTTGTGTTCTAGCTGA-4
34479    TTTGTGTTCTATGAGC-3
34480    TTTGTGTTCTCGTGAA-3
34481    TTTGTGTTCTCTGCGT-4
Name: Unnamed: 0, Length: 34482, dtype: object

In [5]:
barcodes = []
for i in barcode:
    barcodes.append(i[-1])

In [6]:
barcodes

['1',
 '1',
 '3',
 '4',
 '4',
 '4',
 '4',
 '2',
 '2',
 '2',
 '2',
 '4',
 '2',
 '2',
 '4',
 '4',
 '1',
 '3',
 '3',
 '4',
 '2',
 '1',
 '4',
 '3',
 '3',
 '2',
 '2',
 '2',
 '2',
 '1',
 '1',
 '3',
 '4',
 '4',
 '2',
 '2',
 '4',
 '4',
 '1',
 '1',
 '4',
 '3',
 '4',
 '1',
 '3',
 '1',
 '3',
 '2',
 '3',
 '4',
 '1',
 '3',
 '2',
 '1',
 '4',
 '3',
 '3',
 '3',
 '4',
 '3',
 '1',
 '4',
 '3',
 '2',
 '3',
 '4',
 '3',
 '4',
 '3',
 '2',
 '1',
 '2',
 '3',
 '2',
 '4',
 '2',
 '3',
 '2',
 '2',
 '1',
 '2',
 '3',
 '3',
 '4',
 '2',
 '4',
 '3',
 '4',
 '4',
 '2',
 '2',
 '3',
 '2',
 '1',
 '4',
 '3',
 '4',
 '2',
 '4',
 '2',
 '4',
 '1',
 '2',
 '3',
 '1',
 '4',
 '3',
 '1',
 '1',
 '4',
 '2',
 '4',
 '4',
 '3',
 '3',
 '1',
 '3',
 '4',
 '4',
 '2',
 '1',
 '2',
 '2',
 '4',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '4',
 '3',
 '3',
 '2',
 '4',
 '3',
 '4',
 '1',
 '4',
 '2',
 '2',
 '4',
 '4',
 '3',
 '3',
 '3',
 '1',
 '2',
 '3',
 '1',
 '1',
 '1',
 '3',
 '1',
 '2',
 '2',
 '2',
 '4',
 '2',
 '1',
 '4',
 '3',
 '1',
 '3',
 '4',
 '1',
 '3',
 '4',
 '3',
 '1',
 '3',
 '4',
 '3',
 '4',
 '2',
 '4',
 '1',
 '1',
 '4',
 '2',
 '3',
 '3',
 '1',
 '4',
 '4',
 '4',
 '2',
 '1',
 '2',
 '1',
 '4',
 '4',
 '1',
 '2',
 '4',
 '1',
 '1',
 '3',
 '3',
 '3',
 '2',
 '4',
 '3',
 '4',
 '3',
 '2',
 '3',
 '4',
 '3',
 '1',
 '4',
 '3',
 '1',
 '4',
 '3',
 '1',
 '2',
 '3',
 '3',
 '4',
 '4',
 '1',
 '2',
 '2',
 '4',
 '4',
 '4',
 '1',
 '4',
 '1',
 '2',
 '4',
 '4',
 '1',
 '4',
 '1',
 '3',
 '3',
 '2',
 '4',
 '2',
 '4',
 '2',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '4',
 '3',
 '2',
 '1',
 '2',
 '4',
 '3',
 '3',
 '1',
 '3',
 '2',
 '2',
 '2',
 '3',
 '1',
 '4',
 '4',
 '3',
 '3',
 '1',
 '3',
 '4',
 '3',
 '3',
 '4',
 '1',
 '3',
 '2',
 '2',
 '2',
 '2',
 '1',
 '4',
 '3',
 '4',
 '2',
 '1',
 '1',
 '1',
 '4',
 '1',
 '1',
 '3',
 '4',
 '3',
 '4',
 '1',
 '3',
 '3',
 '2',
 '2',
 '4',
 '4',
 '2',
 '2',
 '1',
 '3',
 '2',
 '4',
 '1',
 '2',
 '4',
 '2',
 '4',
 '2',
 '4',
 '4',
 '4',
 '4',
 '1',
 '1',
 '2',
 '2',
 '3',
 '1',
 '3',
 '2',
 '2',
 '2',
 '3',
 '2',
 '3',
 '2',
 '1',
 '2',
 '1',
 '1',
 '4',
 '1',
 '3',
 '1',
 '1',
 '2',
 '3',
 '1',
 '4',
 '4',
 '1',
 '1',
 '2',
 '4',
 '4',
 '2',
 '2',
 '1',
 '1',
 '2',
 '4',
 '2',
 '3',
 '2',
 '1',
 '2',
 '1',
 '4',
 '1',
 '3',
 '3',
 '4',
 '1',
 '1',
 '4',
 '1',
 '2',
 '2',
 '2',
 '3',
 '3',
 '1',
 '1',
 '4',
 '4',
 '1',
 '1',
 '3',
 '2',
 '2',
 '3',
 '4',
 '2',
 '4',
 '4',
 '2',
 '2',
 '3',
 '4',
 '3',
 '1',
 '1',
 '2',
 '4',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '2',
 '1',
 '4',
 '1',
 '2',
 '2',
 '2',
 '4',
 '4',
 '4',
 '4',
 '1',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '4',
 '4',
 '1',
 '2',
 '4',
 '1',
 '2',
 '2',
 '1',
 '3',
 '3',
 '4',
 '1',
 '1',
 '2',
 '3',
 '3',
 '4',
 '3',
 '3',
 '3',
 '3',
 '1',
 '4',
 '2',
 '4',
 '2',
 '1',
 '4',
 '3',
 '3',
 '3',
 '1',
 '1',
 '3',
 '2',
 '3',
 '1',
 '2',
 '1',
 '4',
 '3',
 '1',
 '1',
 '4',
 '3',
 '1',
 '3',
 '3',
 '2',
 '3',
 '1',
 '4',
 '1',
 '2',
 '1',
 '4',
 '1',
 '4',
 '2',
 '2',
 '2',
 '2',
 '3',
 '2',
 '1',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '1',
 '2',
 '3',
 '4',
 '4',
 '1',
 '3',
 '3',
 '2',
 '4',
 '3',
 '2',
 '1',
 '2',
 '4',
 '3',
 '4',
 '3',
 '2',
 '2',
 '3',
 '1',
 '2',
 '4',
 '2',
 '4',
 '3',
 '2',
 '3',
 '3',
 '4',
 '3',
 '2',
 '2',
 '2',
 '3',
 '2',
 '4',
 '1',
 '3',
 '4',
 '4',
 '3',
 '3',
 '4',
 '1',
 '2',
 '4',
 '1',
 '3',
 '3',
 '4',
 '1',
 '2',
 '3',
 '1',
 '2',
 '1',
 '2',
 '4',
 '1',
 '4',
 '2',
 '4',
 '1',
 '4',
 '4',
 '1',
 '3',
 '4',
 '1',
 '4',
 '3',
 '1',
 '1',
 '4',
 '1',
 '4',
 '4',
 '4',
 '1',
 '2',
 '2',
 '1',
 '4',
 '4',
 '4',
 '1',
 '1',
 '3',
 '2',
 '3',
 '4',
 '3',
 '2',
 '1',
 '1',
 '2',
 '1',
 '1',
 '1',
 '3',
 '3',
 '2',
 '4',
 '1',
 '4',
 '1',
 '4',
 '4',
 '2',
 '3',
 '3',
 '1',
 '1',
 '4',
 '1',
 '1',
 '3',
 '4',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '1',
 '4',
 '1',
 '3',
 '1',
 '2',
 '2',
 '1',
 '1',
 '1',
 '4',
 '2',
 '3',
 '1',
 '3',
 '1',
 '1',
 '3',
 '4',
 '4',
 '4',
 '2',
 '2',
 '3',
 '4',
 '3',
 '1',
 '1',
 '2',
 '3',
 '3',
 '1',
 '2',
 '1',
 '4',
 '4',
 '2',
 '1',
 '1',
 '2',
 '2',
 '4',
 '3',
 '2',
 '2',
 '3',
 '2',
 '2',
 '2',
 '1',
 '1',
 '1',
 '1',
 '2',
 '4',
 '1',
 '3',
 '1',
 '4',
 '2',
 '4',
 '4',
 '1',
 '3',
 '4',
 '3',
 '4',
 '4',
 '2',
 '1',
 '2',
 '1',
 '1',
 '4',
 '2',
 '4',
 '4',
 '2',
 '3',
 '4',
 '2',
 '3',
 '4',
 '1',
 '2',
 '2',
 '3',
 '4',
 '3',
 '1',
 '3',
 '2',
 '4',
 '1',
 '3',
 '2',
 '4',
 '2',
 '1',
 '3',
 '3',
 '2',
 '2',
 '4',
 '4',
 '4',
 '3',
 '4',
 '2',
 '1',
 '1',
 '3',
 '3',
 '3',
 '3',
 '4',
 '4',
 '1',
 '4',
 '1',
 '4',
 '2',
 '4',
 '4',
 '3',
 '4',
 '2',
 '4',
 '1',
 '3',
 '4',
 '3',
 '4',
 '4',
 '3',
 '1',
 '4',
 '4',
 '1',
 '3',
 '1',
 '4',
 '4',
 '2',
 '1',
 '4',
 '3',
 '1',
 '2',
 '3',
 '4',
 '1',
 '4',
 '2',
 '2',
 '1',
 '1',
 '2',
 '1',
 '2',
 '3',
 '3',
 '3',
 '1',
 '3',
 '4',
 '2',
 '2',
 '3',
 '4',
 '1',
 '1',
 '1',
 '2',
 '1',
 '3',
 '4',
 '1',
 '2',
 '1',
 '3',
 '3',
 '1',
 '2',
 '1',
 '4',
 '4',
 '1',
 '2',
 '1',
 '4',
 '3',
 '3',
 '2',
 '3',
 '4',
 '1',
 '2',
 '2',
 '2',
 '3',
 '2',
 '4',
 '2',
 '2',
 '4',
 '4',
 '3',
 '4',
 '4',
 '4',
 '2',
 '2',
 '4',
 '4',
 '3',
 '4',
 '4',
 '3',
 '4',
 '1',
 '3',
 '3',
 '3',
 '3',
 '1',
 '3',
 '1',
 '4',
 '3',
 '3',
 '4',
 '2',
 '4',
 '4',
 '3',
 '2',
 '4',
 '3',
 '2',
 '1',
 '2',
 '2',
 '4',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '3',
 '4',
 '4',
 '2',
 '4',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '1',
 '3',
 '4',
 '4',
 '3',
 '3',
 '3',
 '4',
 '3',
 '1',
 '4',
 '2',
 '3',
 '3',
 '4',
 '1',
 '1',
 '4',
 '4',
 '4',
 '1',
 '3',
 '4',
 '4',
 '4',
 '2',
 '4',
 '4',
 '4',
 '3',
 '2',
 '3',
 '1',
 '3',
 '4',
 '4',
 '1',
 '4',
 '3',
 '3',
 '4',
 '3',
 '3',
 '2',
 '3',
 '3',
 '4',
 '2',
 '2',
 '4',
 '4',
 '1',
 '3',
 '3',
 '4',
 '3',
 '2',
 '2',
 '2',
 '3',
 '4',
 '3',
 '1',
 '2',
 '3',
 '1',
 '1',
 '4',
 '3',
 '3',
 '4',
 '4',
 '3',
 '2',
 '2',
 '4',
 '4',
 '4',
 '1',
 '2',
 '4',
 '2',
 '4',
 '4',
 '4',
 '2',
 '4',
 '4',
 '1',
 '4',
 '1',
 '4',
 ...]

In [7]:
metadata["types"] = barcodes

In [8]:
metadata

,Unnamed: 0,orig.ident,nCount_peaks,nFeature_peaks,TSS_fragments,DNase_sensitive_region_fragments,enhancer_region_fragments,promoter_region_fragments,on_target_fragments,blacklist_region_fragments,peak_region_fragments,peak_region_cutsites,passed_filters,duplicate,cell_id,is__cell_barcode,types
0,AAACGAAAGAGAGTAG-1,SeuratProject,15632,6211,4522,6190,3040,4222,8397,17,7943,15632,10220,6529,_cell_0,1,1
1,AAACGAAAGCACGTAG-1,SeuratProject,6930,3036,2390,3396,1540,2110,4352,3,3579,6930,5516,2780,_cell_1,1,1
2,AAACGAAAGCATGTGG-3,SeuratProject,14161,5706,4328,5889,2734,4052,7813,9,7260,14161,9630,6992,_cell_2,1,3
3,AAACGAAAGCTCGGCT-4,SeuratProject,644,337,211,332,170,182,435,3,344,644,595,554,_cell_3,1,4
4,AAACGAAAGGATATCA-4,SeuratProject,43068,14737,13925,22323,11723,11916,28665,240,22681,43068,39266,65612,_cell_4,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34477,TTTGTGTTCGTGGGTC-3,SeuratProject,1019,516,279,484,234,255,586,1,530,1019,730,73,_cell_34477,1,3
34478,TTTGTGTTCTAGCTGA-4,SeuratProject,11851,4968,3512,5438,2554,3262,6714,4,6075,11851,8706,13967,_cell_34478,1,4
34479,TTTGTGTTCTATGAGC-3,SeuratProject,9817,4423,2656,4373,2105,2473,5403,8,5051,9817,6559,2419,_cell_34479,1,3
34480,TTTGTGTTCTCGTGAA-3,SeuratProject,13838,5469,3786,5967,3126,3530,7732,4,7088,13838,9736,19259,_cell_34480,1,3
34481,TTTGTGTTCTCTGCGT-4,SeuratProject,57122,16208,16779,24717,12038,15546,32353,69,29427,57122,40517,91244,_cell_34481,1,4

In [9]:
metadata.loc[metadata.types == "1", 'dtype'] = "P1_R1"
metadata.loc[metadata.types == "2", 'dtype'] = "P1_R2"
metadata.loc[metadata.types == "3", 'dtype'] = "P8_R1"
metadata.loc[metadata.types == "4", 'dtype'] = "P8_R2"

In [10]:
metadata

,Unnamed: 0,orig.ident,nCount_peaks,nFeature_peaks,TSS_fragments,DNase_sensitive_region_fragments,enhancer_region_fragments,promoter_region_fragments,on_target_fragments,blacklist_region_fragments,peak_region_fragments,peak_region_cutsites,passed_filters,duplicate,cell_id,is__cell_barcode,types,dtype
0,AAACGAAAGAGAGTAG-1,SeuratProject,15632,6211,4522,6190,3040,4222,8397,17,7943,15632,10220,6529,_cell_0,1,1,P1_R1
1,AAACGAAAGCACGTAG-1,SeuratProject,6930,3036,2390,3396,1540,2110,4352,3,3579,6930,5516,2780,_cell_1,1,1,P1_R1
2,AAACGAAAGCATGTGG-3,SeuratProject,14161,5706,4328,5889,2734,4052,7813,9,7260,14161,9630,6992,_cell_2,1,3,P8_R1
3,AAACGAAAGCTCGGCT-4,SeuratProject,644,337,211,332,170,182,435,3,344,644,595,554,_cell_3,1,4,P8_R2
4,AAACGAAAGGATATCA-4,SeuratProject,43068,14737,13925,22323,11723,11916,28665,240,22681,43068,39266,65612,_cell_4,1,4,P8_R2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34477,TTTGTGTTCGTGGGTC-3,SeuratProject,1019,516,279,484,234,255,586,1,530,1019,730,73,_cell_34477,1,3,P8_R1
34478,TTTGTGTTCTAGCTGA-4,SeuratProject,11851,4968,3512,5438,2554,3262,6714,4,6075,11851,8706,13967,_cell_34478,1,4,P8_R2
34479,TTTGTGTTCTATGAGC-3,SeuratProject,9817,4423,2656,4373,2105,2473,5403,8,5051,9817,6559,2419,_cell_34479,1,3,P8_R1
34480,TTTGTGTTCTCGTGAA-3,SeuratProject,13838,5469,3786,5967,3126,3530,7732,4,7088,13838,9736,19259,_cell_34480,1,3,P8_R1
34481,TTTGTGTTCTCTGCGT-4,SeuratProject,57122,16208,16779,24717,12038,15546,32353,69,29427,57122,40517,91244,_cell_34481,1,4,P8_R2

In [11]:
metadata.to_csv('singlecell_processed.csv', sep=',', index=False)